//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    using System.Web.Mvc;

    public partial class Sanpham
    {
        public Sanpham()
        {
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
            this.MauSacs = new HashSet<MauSac>();
        }
        
        public int SanphamID { get; set; }
        [DisplayName("Tên sản phẩm")]
        [Required(ErrorMessage = "Tên Sản phẩm là bắt buộc!")]
        public string TenSanpham { get; set; }
        [DisplayName("Mô tả")]
        [Required(ErrorMessage = "Mô tả là bắt buộc!")]
        public string MoTa { get; set; }
        [DisplayName("Giá")]
        [Required(ErrorMessage = "Giá Sản phẩm là bắt buộc!")]
        public decimal Gia { get; set; }
        [DisplayName("Trạng thái")]
        [Required(ErrorMessage = "Trạng thái là bắt buộc!")]
        public Nullable<byte> TrangThai { get; set; }
        [DisplayName("Ảnh đại diện")]
        //[Required(ErrorMessage = "Ảnh đại diện Sản phẩm là bắt buộc!")]
        public string AnhDaiDien { get; set; }
        [DisplayName("Nổi bật")]
        [Required(ErrorMessage = "Nổi bật là bắt buộc!")]
        public Nullable<byte> NoiBat { get; set; }
        [DisplayName("Phân Loại sản phẩm")]
        [Required(ErrorMessage = "Phân Loại là bắt buộc!")]
        public Nullable<int> PhanLoaiSanPhamID { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual PhanLoaiSanPham PhanLoaiSanPham { get; set; }
        public virtual ICollection<MauSac> MauSacs { get; set; }
    }
}
